name = "Ahmed Hezqial Zaidan"
rol = "Website Developer"
email = "hezqilrahmady@gmail.com"
phone = "+62 882-0085-83981"
birthday = "August 12, 2001"
location = "Kota Bekasi, Jawa Barat, Indonesi"
avatar = "./config/assets/avatars/pict-ahz.png"
username = "hezqilzaidan" # <-- github user name
googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d63455.30509765361!2d106.84851812167969!3d-6.269442399999978!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e698d3124723b31%3A0x103e4081d4bfaa26!2sTk%20Permata%20Hati!5e0!3m2!1sid!2sid!4v1724845527934!5m2!1sid!2sid" 
presentation = """
Hi everyone! My name is Ahmed Hezqial Zaidan. I'm a web developer from Bekasi, West Java. I have 1 year of experience Web development. I really enjoy what I do right now, in my opinion, creating programs is not just a job, but also an art that has aesthetic value.

My job is to build your website to be functional and user-friendly yet still attractive. In addition, I provide a personal touch to your product and ensure that the website catches attention and is easy to use. My goal is to convey your message and identity in the most creative way. If you are interested in hiring me, please contact the listed contact.
"""